title: CIE CETYS
description: Centro de Innovacion Educativa - Centro de Enseñanza Técnica y Superior
theme: just-the-docs

url: https://ibnami.github.io/cie-cetys/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
